name: Create Project Template

on:
  workflow_dispatch:
    inputs:
      template_version:
        description: 'Template version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'
        type: string
      include_altlib:
        description: 'Include altlib directory in template'
        required: false
        default: true
        type: boolean

jobs:
  create-template:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create template directory
        run: |
          mkdir -p template-project
          
      - name: Copy template files
        run: |
          # Copy all files from files directory
          cp -r files/* template-project/
          
          # Copy altlib if requested
          if [ "${{ inputs.include_altlib }}" = "true" ]; then
            cp -r altlib template-project/
          fi
          
          # Copy documentation template
          cp altguide.md template-project/PROJECT_SETUP_GUIDE.md
          
      - name: Create template README
        run: |
          cat > template-project/TEMPLATE_README.md << 'EOF'
          # RHS Altium Project Template
          
          This is a project template for Altium Designer projects from RoboticsHardwareSolutions.
          
          ## Contents
          
          - `README.md` - Template README for your project
          - `.github/workflows/` - GitHub Actions workflows for project validation
          - `PCB.PcbDoc` - Altium PCB template
          - `Job.OutJob` - Output job configuration
          - `board_options.txt` - Board fabrication options
          - `ext_bom.csv` - External BOM template
          - `altlib/` - RHS component libraries (if included)
          - `PROJECT_SETUP_GUIDE.md` - Detailed setup guide
          
          ## Usage
          
          1. Extract this template to your new project directory
          2. Rename files as needed for your project
          3. Update README.md with your project information
          4. Follow the setup guide in PROJECT_SETUP_GUIDE.md
          5. Commit to your Git repository
          
          ## Requirements
          
          - Altium Designer
          - Python 3.11+ (for validation scripts)
          
          ## Support
          
          For issues with this template, please create an issue in the altguide repository:
          https://github.com/RoboticsHardwareSolutions/altguide
          EOF
          
      - name: Create template archive
        run: |
          cd template-project
          zip -r ../rhs-altium-template-${{ inputs.template_version }}.zip .
          tar -czf ../rhs-altium-template-${{ inputs.template_version }}.tar.gz .
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: template-${{ inputs.template_version }}
          name: Project Template ${{ inputs.template_version }}
          body: |
            # RHS Altium Project Template ${{ inputs.template_version }}
            
            This release contains a ready-to-use project template for Altium Designer projects.
            
            ## What's included:
            - ✅ Altium PCB and OutJob templates
            - ✅ GitHub Actions workflow for project validation
            - ✅ Documentation templates
            - ✅ Board fabrication options
            - ${{ inputs.include_altlib == 'true' && '✅' || '❌' }} RHS component libraries
            
            ## Download options:
            - **ZIP format**: `rhs-altium-template-${{ inputs.template_version }}.zip`
            - **TAR.GZ format**: `rhs-altium-template-${{ inputs.template_version }}.tar.gz`
            
            ## Quick start:
            1. Download and extract the template
            2. Follow instructions in `TEMPLATE_README.md`
            3. Customize for your project needs
            
            Generated on: ${{ github.run_id }}
          files: |
            rhs-altium-template-${{ inputs.template_version }}.zip
            rhs-altium-template-${{ inputs.template_version }}.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create download artifact
        uses: actions/upload-artifact@v4
        with:
          name: rhs-altium-template-${{ inputs.template_version }}
          path: |
            rhs-altium-template-${{ inputs.template_version }}.zip
            rhs-altium-template-${{ inputs.template_version }}.tar.gz
          retention-days: 30
